version: '3.9'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_a:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data_a: